package org.example;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@Testcontainers // Tells JUnit to manage Docker containers
public class OrderDaoTest {

    // 1. Define the Docker Container (MySQL version 8)
    @Container
    private static final MySQLContainer<?> mysql = new MySQLContainer<>("mysql:8.0.30")
            .withDatabaseName("testdb")
            .withUsername("root")
            .withPassword("password");

    private Connection connection;
    private OrderDao orderDao;

    @BeforeEach
    public void setUp() throws SQLException {
        // 2. Connect to the dynamic port generated by Testcontainers
        connection = DriverManager.getConnection(mysql.getJdbcUrl(), mysql.getUsername(), mysql.getPassword());

        // 3. Create the table for our test
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS orders (id VARCHAR(255) PRIMARY KEY, amount DOUBLE)");
        }

        orderDao = new OrderDaoImpl(connection);
    }

    @AfterEach
    public void tearDown() throws SQLException {
        // Clean up the table after each test
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("DROP TABLE orders");
        }
        connection.close();
    }

    @Test
    public void testSaveOrder() throws SQLException {
        // Arrange
        Order order = new Order("ORD-999", 150.75);

        // Act: Save it using our real implementation
        orderDao.saveOrder(order);

        // Assert: Query the actual database to prove it was saved
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM orders WHERE id = 'ORD-999'")) {

            assertTrue(rs.next(), "The order should exist in the database");
            assertEquals(150.75, rs.getDouble("amount"), "The amount should match");
        }
    }
}